pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        jcenter()
        maven { url 'https://jitpack.io' }
        maven {
            url uri('mint-plugin-repo-5.0.0')
        }
    }
}

rootProject.name = "ACEdns"
include ':app'
//include ':MPChartLib'
include ':library'
