<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit34fbd2373099ce42bfaa5fe51184b8b1
{
    public static $prefixLengthsPsr4 = array (
        'R' => 
        array (
            'Root\\Misreport\\' => 15,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Root\\Misreport\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit34fbd2373099ce42bfaa5fe51184b8b1::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit34fbd2373099ce42bfaa5fe51184b8b1::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit34fbd2373099ce42bfaa5fe51184b8b1::$classMap;

        }, null, ClassLoader::class);
    }
}
