// <att_checkout_info>
//     <attendance_id>
//         <![CDATA[""]]>
//     </attendance_id>
//     <checkout_id>
//         <![CDATA[""]]>
//     </checkout_id>
//     <emp_code>
//         <![CDATA["E0555"]]>
//     </emp_code>
//     <create_date>
//         <![CDATA["2024-03-14"]]>
//     </create_date>
//     <att_starting_km>
//         <![CDATA["140"]]>
//     </att_starting_km>
//     <att_odometer>
//         <![CDATA["209"]]>
//     </att_odometer>
//     <att_necessary_items>
//         <![CDATA[""]]>
//     </att_necessary_items>
//     <att_activities>
//         <![CDATA[""]]>
//     </att_activities>
//     <checkout_ending_km>
//         <![CDATA[""]]>
//     </checkout_ending_km>
//     <checkout_odometer>
//         <![CDATA[""]]>
//     </checkout_odometer>
//     <vehicle_type>
//         <![CDATA[""]]>
//     </vehicle_type>
// </att_checkout_info>